include: package:lints/recommended.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    always_declare_return_types: true
    always_specify_types: true
    flutter_style_todos: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    avoid_dynamic_calls: true
    directives_ordering: true
